apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP # Serivce의 종류 (Default: ClusterIP)
  ports:
    - targetPort: 80 # Pod의 external port, 미입력시 port와 동일
      port: 80 # @Required: 서비스의 포트
  selector:
    tier: be
