# 시크릿 자체 주입
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret1
  labels:
    run: pod-secret1
spec:
  containers:
    - image: nginx
      name: pod-secret1
      envFrom:
        - secretRef:
            name: secret-demo-3
