# 단일 키 주입
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret2
  labels:
    run: pod-secret2
spec:
  containers:
    - image: nginx
      name: pod-secret2
      env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: secret-demo-3
              key: USERNAME
