# 볼륨 마운트
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret3
  labels:
    run: pod-secret3
spec:
  containers:
  - image: nginx
    name: pod-secret3
    volumeMounts:
      - name: secret-vol
        mountPath: "/etc/foo"
  volumes:
    - name: secret-vol
      secret:
        secretName: secret-demo-3
