apiVersion: v1
kind: Pod
metadata:
  name: pod-secret4
  labels:
    run: pod-secret4
spec:
  containers:
    - image: nginx
      name: pod-secret4
      volumeMounts:
        - name: secret-demo
          mountPath: "/config"
  volumes:
    - name: secret-demo
      secret:
        secretName: secret-demo-4
        items:
          - key: USERNAME
            path: "USER_NAME"
