# 볼륨 마운트
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret5
  labels:
    run: pod-secret5
spec:
  containers:
    - image: nginx
      name: pod-secret5
      volumeMounts:
        - name: secret-vol
          mountPath: "/config"
  volumes:
    - name: secret-vol
      secret:
        secretName: secret-demo-5
