apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod2
spec:
  containers:
    - image: k8s.gcr.io/busybox
      name: dapi-test-pod2
      command: [ "/bin/echo", "$(SPECIAL_LELVEL_KEY)", "$(SPECIAL_TYPE_KEY)" ]
      env:
        - name: SPECIAL_LELVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: log_level
  restartPolicy: Never
