apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod3
spec:
  containers:
    - image: k8s.gcr.io/busybox
      name: dapi-test-pod3
      command: [ "/bin/sh", "-c", "ls /etc/config" ]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never
