apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod1
spec:
  containers:
  - image: k8s.gcr.io/busybox
    name: dapi-test-pod1
    command: ["/bin/sh", "-c", "env"]
    env:
      - name: SPECIAL_LELVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: env-config
            key: log_level
