apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
    - image: nginx
      name: env-single-secret
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-user
              key: backend-username
