apiVersion: v1
kind: Pod
metadata:
  name: pod-env-from-secret
spec:
  containers:
    - image: nginx
      name: pod-env-from-secret
      envFrom:
        - secretRef:
            name: test-secret
