apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - image: nginx
    name: secret-test-pod
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
