apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap3
  labels:
    run: pod-configmap3
spec:
  containers:
  - image: nginx
    name: pod-configmap3
    volumeMounts:
      - name: config-map-vol
        mountPath: "/etc/foo"
  volumes:
    - name: config-map-vol
      configMap:
        name: configmap-demo-4
